# Default values for istio-bookinfo.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

global:
  prefix: 'bookinfo'
  reviews:
    versions: [v1,v2,v3]
    port: 9080
    replicas: 1
    imageTag: latest
  details:
    port: 9080
    replicas: 1
    imageTag: latest
  ratings:
    port: 9080
    replicas: 1
    imageTag: latest
  productpage:
    port: 9080
    replicas: 1
    imageTag: latest
  cluster: mgmt
istio:
  tag: 1-16